---
language: python
python:
  - "3.7"
branches:
  only:
    - master

services:
  - docker
install:
  - pip3 install -r requirements.txt
  - pip3 install black

before_install:
  - cd backend/app/

script:
  - pytest tests/ -v

...
