version: '2.4'

services:
    web:
        image: alpharoy2/getvaccindia:latest
        command: sh -c "chmod +x start_web.sh && ./start_web.sh"
        ports:
            - 80:80
        environment:
            - ENVIRONMENT=prod
            - PYTHONPATH=/usr/src/app
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        env_file:
            - .env
        depends_on:
            - redis

    worker:
        image: alpharoy2/getvaccindia:latest
        command: sh -c "chmod +x start_workers.sh && ./start_workers.sh"
        environment:
            - ENVIRONMENT=dev
            - PYTHONPATH=/usr/src/app
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        restart: always
        depends_on:
            - web
            - redis
            - producer
        env_file:
            - .env
    producer:
        image: alpharoy2/getvaccindia:latest
        command: sh -c "chmod +x start_scheduler.sh && ./start_scheduler.sh"
        environment:
            - ENVIRONMENT=dev
            - PYTHONPATH=/usr/src/app
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        restart: always
        env_file:
            - .env
        depends_on:
            - web
            - redis

    redis:
        image: redis:6-alpine

